### ISSUE TITLE
Context Variable changes during rule application

### ISSUE THREAD

**Issue by mqhashim** [meta-logic/sequoia-v0#21]
applying the following rule :
Premise: \Gamma \vdash \Delta                 Conclusion:   \Delta \vdash \Gamma
on the sequent  (G \vdash B)  causes the premise to be the premise of the rule, and the rule can't be applied anymore.

**Comment by mqhashim** [comment]
![Screenshot from 2019-10-09 02-19-27](https://user-images.githubusercontent.com/36605210/66440323-52861600-ea3b-11e9-97dd-a8e107777c6c.png)

**Comment by znaeem** [comment]
Fixed with constraints
