### ISSUE TITLE
Add atoms to parser

### ISSUE THREAD

**Issue by gisellemnr** [meta-logic/sequoia-v0#7]
The parser should be able to parse not only atom variables, but also atoms.

**Comment by znaeem** [comment]
Added the atoms.

**Comment by gisellemnr** [comment]
Where is it? I don't see a commit.

**Comment by znaeem** [comment]
Here is the parser text:

// Sequent
SEQ
  = _ ctx1:CTX_STR _ seq_sign:SeqSign _ ctx2:CTX_STR _{ return "Seq (" + ctx1 + ', Con ("' + seq_sign + '"), ' + ctx2 + ")" }

// Context struct
CTX_STR
  = ctx:CTX _ ctx_sep:CtxSep _ ctx_str:CTX_STR { return "Mult ( Con (" + ctx_sep + "), " + ctx + ", " + ctx_str + ")" }
  / ctx:CTX { return "Single (" + ctx + ")" }

// Context
CTX
  = ctx_lst:CTX_LST {
    var [ctx_vars, forms] = ctx_lst
    var c = ctx_vars.join(" :: ")
    var f = forms.join(" :: ")
    return "Ctx ([" + c + "], [" + f + "])"
  }

CTX_LST
  = ctx_var:CTX_VAR _ "," _ ctx_lst:CTX_LST {
      var [ctx_vars, forms] = ctx_lst
      ctx_vars.push(ctx_var)
      return [ctx_vars, forms]
    }
  / form:F _ "," _ ctx_lst:CTX_LST _ {
      var [ctx_vars, forms] = ctx_lst
      forms.push(form)
      return [ctx_vars, forms]
    }
  / ctx_var:CTX_VAR { return [[ctx_var], []] }
  / form:F { return [[], [form]] }

// Formula
F = BIFORM / FORM

SUB_FORMS = _ fr:FORM _ "," _ rest:SUB_FORMS {return  fr + "::" + rest}  /
_ fr:FORM _ {if (fr == "NONE") { return "nil" }
         else { return fr + "::nil" }}

BIFORM
  = fr:FORM _ conn:CONN _ fr2:FORM
  {return "Form (" + conn + ", [" + fr + "," + fr2 + "])" }


FORM
  =
  "(" _ form:BIFORM _ ")" { return form }
  / conn:CONN _ form:FORM { return "Form (" + conn + ", [" + form + "])" }
  / conn:CONN _ "(" _ fls:SUB_FORMS _ ")" {return 'Form(' + conn + "," + fls + ")"}
  / form_var:FORM_VAR { return form_var }
  / atom_var:ATOM_VAR { return atom_var }
  / atom:ATOM { return atom }

// Symbols
CONN = conn:Conn { return 'Con ("' + conn  + '")' }
CTX_VAR = ctx_var:CtxVar { return 'CtxVar ("' + ctx_var + '")' }
FORM_VAR = form_var:FormVar { return 'FormVar ("' + form_var + '")' }
ATOM_VAR = atom_var:AtomVar { return 'AtomVar ("' + atom_var + '")' }
ATOM = atom:Atom { return 'Atom ("' + atom + '")' }

_ "whitespace"
  = [ ]*
